#CONFIGURACION DEL PUERTO DEL SERVIDOR
server.port=${DTODO_PROD_API_PORT:8382}
server.tomcat.connection-timeout=20000

# CONFIGURACION CERTIFICADO SSL PROTOCOLO HTTPS
server.ssl.key-store=classpath:keystore/dtodo-certificate-2025-PKCS.p12
server.ssl.key-store-type=pkcs12
server.ssl.key-store-password=12345
server.ssl.key-password=12345
server.ssl.key-alias=dtodo2025
server.ssl.enabled=true

#JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL57Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=600000

# HOSTING VPS
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${DTODO_PROD_DB_HOST:localhost}:${DTODO_PROD_DB_PORT:3306}/${DTODO_PROD_DB_NAME:prstd_db}?useSSL=false
spring.datasource.username=${DTODO_PROD_DB_USERNAME:root}
spring.datasource.password=${DTODO_PROD_DB_PASSWORD:1992}


#TIMEZONE
spring.jackson.time-zone=America/Guatemala
spring.jackson.locale=es_GT

# LOGGING
logging.level.root=ERROR
logging.level.com.aglayatech.licorstore=DEBUG
logging.level.com.aglayatech.licorstore.controller=DEBUG
logging.level.com.aglayatech.licorstore.service=DEBUG
logging.level.com.aglayatech.licorstore.auth=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping = ERROR
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor=ERROR
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter=ERROR
logging.file.name=${DTODO_PROD_LOG_FILENAME:/var/apps/dtodo/api/backend/logs/spring.log}