CREATE FUNCTION `get_cant_ventas`() RETURNS int 
BEGIN 
	DECLARE MAXSALES INT;
	DECLARE CANTSALES INT;
	SELECT
	    COUNT(1) INTO MAXSALES
	FROM
	    facturas
	WHERE
	    id_estado <> 4;
	SET CANTSALES = MAXSALES;
	RETURN CANTSALES;
END; 